### PR TITLE
Dockerfile & docker-compose setup

### LINKED ISSUE #12: Set up Docker

### PR DESCRIPTION
**Pull request by notarock**
# Dockerfile

- Build container using docker
- Development docker-compose setup (Just do `docker-compose up` and code)

I can't get https to works in this. I'm not sure we _really_ need to enforce https when developing, but maybe I'm missing something? 

image

Maybe there's something missing in the README?

### CODE REVIEW

**Comment by notarock** [comment]
Should close #12

**Comment by petak5** [comment]
To make the server work you have to change `HOST` variable in `src/runserver.py` to `'0.0.0.0'` from `localhost`. After that you should be able to reach the server but it will give you an error because of broken `/version` route (which is alias for the root `/` route) so you have to delete lines with `flask-mysql_version` and `pymysql_version` in `src/api/endpoints.py`.

I am sorry for the inconvenience but we somehow forgot to delete those lines after changing the way we access the database.

**Comment by notarock** [comment]
If you want to test this, simply run `docker-compose up` and it should launch.

**Review by petak5 — APPROVED** [review]
Looks rock solid!

**Pull request merged**
